REQUESTS_MAP = {
    "Service Request (SR) Number": "service_request_sr_number",
    "Department": "department",
    "Group Description": "group_description",
    "SR Description": "sr_description",
    "Method Received": "method_received",
    "SR Status": "sr_status",
    "Is Duplicate? (1/0)": "is_duplicate_1_0",
    "Status Change Date": "status_change_date",
    "Created Date": "created_date",
    "Overdue On Date": "overdue_on_date",
    "Last Update Date": "last_update_date",
    "Close Date": "close_date",
    "SR Age (days)": "sr_age_days",
    "Response Days": "response_days",
    "Open Count": "open_count",
    "Closed Count": "closed_count",
    "Overdue Count": "overdue_count",
    "Closed on Time": "closed_on_time",
    "Closed Late": "closed_late",
    "# of Days Late": "of_days_late",
    "SR Location": "sr_location",
    "State Plane X Coordinate": "state_plane_x_coordinate",
    "State Plane Y Coordinate": "state_plane_y_coordinate",
    "location": "location",
    "fiscal_year": "fiscal_year",
}

FLEX_NOTES_MAP = {
    "Flex Notes ID": "flex_note_id",
    "Service Request Number": "service_request_number",
    "Flex Notes Definition ID": "flex_notes_definition_id",
    "Service Request ID": "service_request_id",
    "Flex Question": "flex_question",
    "Flex Answer": "flex_answer",
}

ACTIVITIES_MAP = {
    "Service Request (SR) Number": "service_request_sr_number",
    "Activity ID": "activity_id",
    "Activity ": "activity",
    "Created Date/Time": "created_date_time",
    "Due Date": "due_date",
    "Completed Date": "completed_date",
    "Outcome ": "outcome",
    "Activity Details": "activity_details",
}
